# Generated by Django 4.2.6 on 2023-10-18 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_studentposition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentPosition',
        ),
    ]
