# Generated by Django 4.2.6 on 2023-10-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_student_teachers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentPosition',
        ),
    ]
